apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: checkoutservice
build:
  artifacts:
  - image: checkoutservice
    context: .
    docker:
      dockerfile: Dockerfile
  #tagPolicy:
  #  gitCommit: {}
deploy:
  kubectl:
    manifests:
    - k8s/checkoutservice.yaml
profiles:
# "gcb" profile allows building and pushing the images
# on Google Container Builder without requiring docker
# installed on the developer machine. However, note that
# since GCB does not cache the builds, each build will
# start from scratch and therefore take a long time.
#
# This is not used by default. To use it, run:
#     skaffold run -p gcb
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 100
      machineType: N1_HIGHCPU_32
      timeout: 4000s
portForward:
- resourceType: deployment
  resourceName: frontend
  port: 8080 
